sonar.projectKey=rakkoons-api
sonar.projectName=Rakkoons API

sonar.sources=src
sonar.tests=test
sonar.sourceEncoding=UTF-8

sonar.exclusions=src/generated/**,src/**/*.spec.ts,dist/**,coverage/**,prisma/migrations/**
sonar.coverage.exclusions=src/main.ts,src/**/*.module.ts,src/generated/**,test/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.tsconfigPath=tsconfig.json
