export const IdentityToken = {
  AccountRepository: Symbol('AccountRepository'),
  VerificationJourneyRepository: Symbol('VerificationJourneyRepository'),
  SessionRepository: Symbol('SessionRepository'),
  PasswordHasher: Symbol('PasswordHasher'),
  SecretHasher: Symbol('SecretHasher'),
  VerificationCodeGenerator: Symbol('VerificationCodeGenerator'),
  IdentifierGenerator: Symbol('IdentifierGenerator'),
  SecretGenerator: Symbol('SecretGenerator'),
  MessageSender: Symbol('MessageSender'),
  SignInCodeThrottle: Symbol('SignInCodeThrottle'),
  EmailTransport: Symbol('EmailTransport'),
  UnitOfWork: Symbol('UnitOfWork'),
  Clock: Symbol('Clock'),
  RegistrationPolicy: Symbol('RegistrationPolicy'),
  SignInCodePolicy: Symbol('SignInCodePolicy'),
  EmailChangePolicy: Symbol('EmailChangePolicy'),
  AccountDeletionPolicy: Symbol('AccountDeletionPolicy'),
  PasswordResetPolicy: Symbol('PasswordResetPolicy'),
  SessionPolicy: Symbol('SessionPolicy'),
  RegistrationJourneyOpener: Symbol('RegistrationJourneyOpener'),
  SignInCodeJourneyOpener: Symbol('SignInCodeJourneyOpener'),
  EmailChangeJourneyOpener: Symbol('EmailChangeJourneyOpener'),
  PasswordResetJourneyOpener: Symbol('PasswordResetJourneyOpener'),
} as const;
